ARG version
FROM almalinux:${version}
ARG course="Devops With Aws" \
    duration="120hrs" \
    topic="Ansible"
RUN echo "course: $course, duration: $duration, topic: $topic"    
CMD ["sleep", "100"]    
